# Generated by Django 5.2 on 2025-07-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='coverImage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
