# Generated by Django 5.2 on 2025-07-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_blog_coverimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='authorAvatar',
        ),
        migrations.AddField(
            model_name='blog',
            name='author_avatar',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='coverImage',
            field=models.CharField(blank=True, null=True),
        ),
    ]
