# Generated by Django 5.2 on 2025-08-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_blog_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
